### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by cosmo0920**
* And update documentation to follow this change
* Tweak Travis CI settings to launch mysql service explicitly

### CODE REVIEW

**Comment by y-ken** [comment]
Thank you. 🙇  added you as rubygems owner member.
https://rubygems.org/gems/fluent-plugin-mysql-replicator

**Comment by cosmo0920** [comment]
Thanks again!

**Comment by cosmo0920** [comment]
I've released v1.0.0 into rubygems.org!
https://rubygems.org/gems/fluent-plugin-mysql-replicator/versions/1.0.0

**Comment by y-ken** [comment]
Sounds great

**Comment by y-ken** [comment]
@shunta27 here is new version that you would like to see. (I noticed you fork this repo.)

**Pull request merged**
