### PR TITLE
Use router.emit instead of Engine.emit

### PR DESCRIPTION
**Pull request by cosmo0920**
Fluentd 0.10.58 or later supports router.emit API.

### CODE REVIEW

**Comment by y-ken** [comment]
Hi @cosmo0920 
Would you please keep backward compatibility?
https://github.com/y-ken/fluent-plugin-mysql-query/pull/8

**Comment by cosmo0920** [comment]
OK, I'll try it.
But, I have not enough time to keep backward compatibility work until tonight..., sorry to delay.

**Comment by y-ken** [comment]
Thank you!

**Comment by cosmo0920** [comment]
I've added keeping backward compatibility hack commit!

**Comment by y-ken** [comment]
Thank you for your perfect coding!

**Comment by cosmo0920** [comment]
Thank you for merging!

**Comment by y-ken** [comment]
I have released v0.5.0 today!
https://rubygems.org/gems/fluent-plugin-mysql-replicator

**Pull request merged**
